version: "3.8"

services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - auth-api
      - todos-api
      - users-api
    env_file:
      - .env

  auth-api:
    build: ./auth-api
    ports:
      - "8080:8080"
    depends_on:
      - redis
    env_file:
      - .env

  todos-api:
    build: ./todos-api
    ports:
      - "3000:3000"
    depends_on:
      - redis
    env_file:
      - .env

  users-api:
    build: ./users-api
    ports:
      - "8081:8081"
    depends_on:
      - redis
    env_file:
      - .env

  log-message-processor:
    build: ./log-message-processor
    depends_on:
      - redis
    env_file:
      - .env

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
